In [ ]:
# Day 2
# june 3

In [ ]:
# Numpy(Numeric Python):

# NumPy is an open source library available in Python that aids in mathematical, scientific, engineering, and data science programming.
# It works perfectly well for multi-dimensional arrays and matrices multiplication.
#NumPy arrays are a bit like Python lists, but still very much different at the same time.


In [1]:
#check numpy installed or not
import numpy as np
print(np.__version__)

2.3.5


In [9]:

lists = [1,2,3,4,5]
numpy_array= np.array(lists)
print(numpy_array)
a=np.array([1,9,8,3])
print(a)
print('the type is :',type(a))


[1 2 3 4 5]
[1 9 8 3]
the type is : <class 'numpy.ndarray'>


In [10]:
#addition 
numpy_array = np.array([1,2,3,4,5,6,7,8,9])
numpy_array +1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#substraction
numpy_array-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
#multiplication
numpy_array*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
#division
numpy_array/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
#checking shapes and dtypes of numpy array

In [16]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.shape)
print(a.dtype)

(8,)
int64


In [17]:
b = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [18]:
ar = np.array([(1,2,3,4,5,6),
              (4,5,6,7,8,7)])
print(ar)
print(ar.shape)


[[1 2 3 4 5 6]
 [4 5 6 7 8 7]]
(2, 6)


In [19]:
ar = np.array([
    [[1, 2, 3, 6, 7],
     [4, 5, 6, 6, 8]],

    [[7, 8, 9, 0, 0],
     [10, 11, 12, 8, 3]]
])

print(ar.shape)

(2, 2, 5)


In [ ]:
#creating numpy array with zeros and ones

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [22]:
# reshaping the dimentions in numpy array
 # product of new shape dimensions = total number of elements

In [24]:

e = np.array([(1,2,3), (4,5,6)])
reshape_e=e.reshape(3,2)
print("original:",e,"\n")
print("after reshape:",reshape_e)

original: [[1 2 3]
 [4 5 6]] 

after reshape: [[1 2]
 [3 4]
 [5 6]]


In [25]:
e = np.array([(1,2,3), (4,5,6)])

reshape_e=e.reshape(-1)  # 1D array

print("original:",e,"\n")
print("after reshape:",reshape_e)

original: [[1 2 3]
 [4 5 6]] 

after reshape: [1 2 3 4 5 6]


In [ ]:
#flat the numpy array

In [26]:
a = np.array([(1,2,3), (4,5,6)]) 
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [27]:
a = np.array([(1,2,3), (4,5,6)])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Stackings on numpy array.

In [28]:
# With hstack we can appened data horizontally.

a = np.array([1,2,3])
b = np.array([4,5,6])

print("a:",a,"\n")
print("b:",b,"\n")
print('Horizontal Append:', np.hstack((a, b)))


a: [1 2 3] 

b: [4 5 6] 

Horizontal Append: [1 2 3 4 5 6]


In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a, "\n")
print("b:", b, "\n")

print("Vertical Stack:")
print(np.vstack((a, b)))

a: [1 2 3] 

b: [4 5 6] 

Vertical Stack:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Generating random numbers


In [30]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2)) # no need to give size param

[[0.50422195 0.58079251]
 [0.77831143 0.18409022]]


In [31]:
# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

[[-0.57899513 -0.00775476]
 [ 2.27310341 -0.44681663]]


In [32]:
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

[[1 8]
 [5 7]]


In [33]:
# One random number between [0,1)
print(np.random.random())

0.961090250682678


In [34]:
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[1.60896184e-04 7.98432555e-01]
 [9.18545635e-01 8.96009085e-01]]


In [35]:
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=(3)))

['o' 'o' 'o']


In [36]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=3, p=[0.3, 0.1,0.1, 0.4, 0.1]))

['o' 'a' 'o']


In [ ]:
#Basic Statistics on numpy array

In [37]:
normal_array = np.random.randn(3, 3)

# Min
print("Min:", np.min(normal_array))

# Max
print("Max:", np.max(normal_array))

# Mean
print("Mean:", np.mean(normal_array))

# Median
print("Median:", np.median(normal_array))

# Standard Deviation
print("Std:", np.std(normal_array))

Min: -1.2550967885573479
Max: 1.4516121673843612
Mean: 0.2689465633772793
Median: 0.10893403400347998
Std: 0.8211767653563035


In [ ]:
#Matrix Operations

In [39]:
# The determinant of an array
import scipy.linalg as slin

a = np.array([[ 3, -5, 8],
 [-1, 2, 3],
 [-5, -6, 2]])

print(slin.det(a))

259.0


In [40]:
#The trace of an array is found by using the trace() function from numpy.

a = np.array([[ 3, -5, 8],
             [-1, 2, 3],
            [-5, -6, 2]])

print(np.trace(a))


7


In [41]:
# Inverse of a matrix is computed from scipy.linalg.inv() function

a = np.array([[ 3, -5, 8],
                [-1, 2, 3],
               [-5, -6, 2]])
slin.inv(a)

array([[ 0.08494208, -0.14671815, -0.11969112],
       [-0.05019305,  0.17760618, -0.06563707],
       [ 0.06177606,  0.16602317,  0.003861  ]])

In [42]:

a = np.array([[ 3, -5, 8],
           [-1, 2, 3],
           [-5, -6, 2]])
np.transpose(a)

array([[ 3, -1, -5],
       [-5,  2, -6],
       [ 8,  3,  2]])

In [ ]:
#for multiplication we this is needed (m, n) × (n, p) → (m, p)

In [43]:
a=np.matrix([[ 3, -5, 8],
             [ 3, -5, 8],
            [-1, 2, 3],
           [-5, -6, 2]])

print(a.shape)

b=np.matrix([[ 3],
           [ 4],
           [-1]])

print(b.shape)
 
c=a*b

print(c.shape)

c

(4, 3)
(3, 1)
(4, 1)


matrix([[-19],
        [-19],
        [  2],
        [-41]])